name: Plumbus-CI
permissions:
  contents: read

on:
- push
- pull_request

jobs:
    build-plumbus:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v6
            - name: build toolchain container
              run: docker build . -t builder
            - uses: ammaraskar/gcc-problem-matcher@master
            - name: build Plumbus
              run: docker run --rm -v ${PWD}:/app -w /app builder
            - uses: actions/upload-artifact@v6
              with:
                  name: plumbus
                  path: dist/
